version: '2'
services:

  frontend:
    build:
      context: ./frontend/snap
    ports:
     - "1410:3000"
    environment:
      BACKEND_URL: "backend"

  backend:
    build:
      context: ./backend/snap
    ports:
     - "1411:1337"
