version: '2'
services:

  frontend:
    build:
      context: ./frontend/snap
    ports:
     - "1410:3000"
    environment:
      BACKEND_URL: "backend"

  backend:
    build:
      context: ./backend/snap
    ports:
     - "1411:1337"

  mongo:
    image: 'mongo:latest'
    ports:
     - "27017:27017"
    environment:
      MONGODB_USER: "mongo" 
      MONGODB_PASS: "mongo"
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
